version: '3.7'
services:
  auth_service:
    build:
      context: .
    restart: 'no'
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
    networks:
      - proradio

networks:
  proradio:
    name: proradio
